image: node:latest

cache:
    paths:
        - node_modules/
        
before_script:
    - npm install
    
stages:
    - build
    
build_prod:
    stage: build
    only: /^stable\/.*/
    script:
        - npm run prod