export const UI_TOGGLE_SIDEBAR = "UI_TOGGLE_SIDEBAR",
             UI_GLOBAL_PLAYER_LOAD = "UI_GLOBAL_PLAYER_LOAD";

export const AUTH_USER = "AUTH_USER",
             AUTH_LOGOUT = "AUTH_LOGOUT";

export const LIBRARY_ADD = "LIBRARY_ADD",
             LIBRARY_LOAD = "LIBRARY_LOAD";

export const GLOBAL_PLAYER_LOAD = "GLOBAL_PLAYER_LOAD",
             GLOBAL_PLAYER_REPEAT = "GLOBAL_PLAYER_REPEAT",
             GLOBAL_PLAYER_CHANGE_CURRENT = "GLOBAL_PLAYER_CHANGE_CURRENT",
             GLOBAL_PLAYER_ADD_TO_PLAYLIST = "GLOBAL_PLAYER_ADD_TO_PLAYLIST",
             GLOBAL_PLAYER_REMOVE_FROM_PLAYLIST = "GLOBAL_PLAYER_REMOVE_FROM_PLAYLIST",
             GLOBAL_PLAYER_LOAD_PLAYLIST = "GLOBAL_PLAYER_LOAD_PLAYLIST",
             GLOBAL_PLAYER_UPDATE_STATE = "GLOBAL_PLAYER_UPDATE_STATE";

export const PLAYLIST_LOAD = "PLAYLIST_LOAD",
             PLAYLIST_LOAD_MANY = "PLAYLIST_LOAD_MANY",
             PLAYLIST_REMOVE = "PLAYLIST_REMOVE",
             PLAYLIST_ADD_SONG = "PLAYLIST_ADD_SONG";