export const UI_TOGGLE_SIDEBAR = "UI_TOGGLE_SIDEBAR",
             UI_GLOBAL_PLAYER_LOAD = "UI_GLOBAL_PLAYER_LOAD";

export const AUTH_USER = "AUTH_USER",
             AUTH_LOGOUT = "AUTH_LOGOUT";

export const LIBRARY_ADD = "LIBRARY_ADD",
             LIBRARY_LOAD = "LIBRARY_LOAD";

export const PLAYERS_LOAD = "PLAYERS_LOAD",
             PLAYERS_SET_READY = "PLAYERS_SET_READY",
             PLAYERS_REPEAT = "PLAYERS_REPEAT",
             PLAYERS_CHANGE_CURRENT = "PLAYERS_CHANGE_CURRENT",
             PLAYERS_LOAD_PLAYLIST = "PLAYERS_LOAD_PLAYLIST",
             PLAYERS_UPDATE_STATE = "PLAYERS_UPDATE_STATE",
             PLAYERS_LOAD_PLAY_SONG = "PLAYERS_LOAD_PLAY_SONG";

export const PLAYER_MANAGER_LOAD_GLOBAL = "PLAYER_MANAGER_LOAD_GLOBAL";

export const PLAYLIST_LOAD = "PLAYLIST_LOAD",
             PLAYLIST_LOAD_MANY = "PLAYLIST_LOAD_MANY",
             PLAYLIST_REMOVE = "PLAYLIST_REMOVE",
             PLAYLIST_ADD_SONG = "PLAYLIST_ADD_SONG",
             PLAYLIST_REMOVE_SONG = "PLAYLIST_REMOVE_SONG",
             PLAYLIST_RENAME = "PLAYLIST_RENAME";